### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by samuelba** [samuelba/google-chat-standup-bot#2]
- [ ] Add more unit tests
- [x] To join a room to a team, it should leave first if it is already assigned to a team (add slash command `/leave_team`) #4 
- [x] It should be only possible to join the room to a team if the team has no other room assigned yet #4 
- [x] Slash command to delete a team if it has no more members `/remove_team TEAM` #5 
- [ ] Rethink the slash commands that are possible in a room
- [x] Make the questions configurable by the team (goes a bit further than https://github.com/samuelba/google-chat-standup-bot/pull/3) #6 
  - [x] New db table questions(id (int), team_id (int), question (varchar), order(int)) #6 
    - [x] Refer in the standups table to the question_id instead of the question_type #6 
  - [x] Slash command to reorder questions `/reorder_questions` --> publish a card to the user with the questions (user has to click the questions in the order he wants them (update card with the order?) #6 
  - [x] Slash command to delete a question `/delete_question` --> publish a card to the user with the questions (user has to click on delete) #6 
  - [x] Slash command to add a question `/add_question QUESTION` #6 
  - [x] Add the default three questions to the team when created #6 
- [x] Use a card to enable/disable schedules #10
